services:
  zenn:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        ENV_USERNAME: zenn
        ENV_WORKDIR: /workspace
    ports:
      - "8080:8000"
    volumes:
      - ..:/workspace:cache
      - node_modules:/workspace/node_modules
    command: /bin/sh -c "yarn zenn preview"

volumes:
  node_modules:
